# This file was generated by GoReleaser. DO NOT EDIT.
cask "orchard" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "71a8caf7351efeeab796cef1cd03959b0971d2b33201c2730e27cf0ff8053ed6"
      url "https://github.com/rahulkj/orchard/releases/download/v#{version}/orchard_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d5407db00bfb42afb4fa44f9d3ba09ab903db55dc04f4ce75102ec69b8fd613a"
      url "https://github.com/rahulkj/orchard/releases/download/v#{version}/orchard_darwin_arm64.tar.gz"
    end
  end

  name "orchard"
  desc "Kubernetes clusters where every node is its own apple/container VM"
  homepage "https://github.com/rahulkj/orchard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orchard"

  # No zap stanza required

end
