# This file was generated by GoReleaser. DO NOT EDIT.
cask "orchard" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "84a3b7a72fa4fb308b76ddb053b515326fa7bf5d25374d85ec4f1ce839829b57"
      url "https://github.com/rahulkj/orchard/releases/download/v#{version}/orchard_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6e8030bc754abc685de2fe2624e6bb6a6d52eed2e33c9b21f60d3e7fa6ded68"
      url "https://github.com/rahulkj/orchard/releases/download/v#{version}/orchard_darwin_arm64.tar.gz"
    end
  end

  name "orchard"
  desc "Kubernetes clusters where every node is its own apple/container VM"
  homepage "https://github.com/rahulkj/orchard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orchard"

  # No zap stanza required

end
