# This file was generated by GoReleaser. DO NOT EDIT.
cask "orchard" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "d6fc6fd01016198fc7883ea9b42340b9c748026afa13e9618af36de69a622ae5"
      url "https://github.com/rahulkj/orchard/releases/download/v#{version}/orchard_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf36300dc211bb909d67548ab4f62e3790387e97726658680ad138974b8989fc"
      url "https://github.com/rahulkj/orchard/releases/download/v#{version}/orchard_darwin_arm64.tar.gz"
    end
  end

  name "orchard"
  desc "Kubernetes clusters where every node is its own apple/container VM"
  homepage "https://github.com/rahulkj/orchard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orchard"

  # No zap stanza required

end
